name: craigbrinks
favicon: null
layout_spectrum: 0.45438423776067793
typography_spectrum: 0.5887565806042403
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.19947611773386598
  lightness: 0.4778910556342453
  saturation: 0.4118437166325748
  rhythmicContrast: 0.5114264506846666
purpose: []
